apiVersion: v1
kind: ConfigMap
metadata:
  name: etherpad-settings
data:
  settings.json: |
    {
      "title": "Lab Etherpad",
      "favicon": "favicon.ico",
      "skinName": "colibris",
      "skinVariants": "light-toolbar dark-background light-editor full-width-editor",
      "ip": "0.0.0.0",
      "port": 9001,
      "showSettingsInAdminPage": true,
      "dbType": "postgres",
      "dbSettings": {
        "host"    : "etherpad-db",
        "port"    : "5432",
        "database": "etherpad-db",
        "user"    : "etherpad",
        "password": "pass"
      },
      "padOptions": {
        "noColors":         false,
        "showControls":     true,
        "showChat":         true,
        "showLineNumbers":  true,
        "useMonospaceFont": false,
        "userName":         false,
        "userColor":        false,
        "rtl":              false,
        "alwaysShowChat":   false,
        "chatAndUsers":     false,
        "lang":             "en-us"
      },
      "padShortcutEnabled" : {
        "altF9":     true, /* focus on the File Menu and/or editbar */
        "altC":      true, /* focus on the Chat window */
        "cmdShift2": true, /* shows a gritter popup showing a line author */
        "delete":    true,
        "return":    true,
        "esc":       true, /* in mozilla versions 14-19 avoid reconnecting pad */
        "cmdS":      true, /* save a revision */
        "tab":       true, /* indent */
        "cmdZ":      true, /* undo/redo */
        "cmdY":      true, /* redo */
        "cmdI":      true, /* italic */
        "cmdB":      true, /* bold */
        "cmdU":      true, /* underline */
        "cmd5":      true, /* strike through */
        "cmdShiftL": true, /* unordered list */
        "cmdShiftN": true, /* ordered list */
        "cmdShift1": true, /* ordered list */
        "cmdShiftC": true, /* clear authorship */
        "cmdH":      true, /* backspace */
        "ctrlHome":  true, /* scroll to top of pad */
        "pageUp":    true,
        "pageDown":  true
      },
      "suppressErrorsInPadText": false,
      "requireSession": false,
      "editOnly": false,
      "sessionNoPassword": false,
      "minify": true,
      "maxAge": 21600, // 60 * 60 * 6 = 6 hours
      "abiword": null,
      "soffice": null,
      "tidyHtml": null,
      "allowUnknownFileEnds": true,
      "requireAuthentication": false,
      "requireAuthorization": false,
      "trustProxy": false,
      "disableIPlogging": false,
      "automaticReconnectionTimeout": 0,
      "scrollWhenFocusLineIsOutOfViewport": {
        "percentage": {
          "editionAboveViewport": 0,
          "editionBelowViewport": 0
        },
        "duration": 0,
        "scrollWhenCaretIsInTheLastLineOfViewport": false,
        "percentageToScrollWhenUserPressesArrowUp": 0
      },
      "users": {
        "admin": {
          "password": "admin",
          "is_admin": true
        }
      },
      "socketTransportProtocols" : ["xhr-polling", "jsonp-polling", "htmlfile"],
      "loadTest": false,
      "indentationOnNewLine": false,
      "importExportRateLimiting": {
        // duration of the rate limit window (milliseconds)
        "windowMs": 90000,

        // maximum number of requests per IP to allow during the rate limit window
        "max": 10
      },
      "importMaxFileSize": 52428800, // 50 * 1024 * 1024
      "toolbar": {
        "left": [
          ["bold", "italic", "underline", "strikethrough"],
          ["orderedlist", "unorderedlist", "indent", "outdent"],
          ["undo", "redo"],
          ["clearauthorship"]
        ],
        "right": [
          ["importexport", "timeslider", "savedrevision"],
          ["settings", "embed"],
          ["showusers"]
        ],
        "timeslider": [
          ["timeslider_export", "timeslider_returnToPad"]
        ]
      },
      "exposeVersion": false,
      "loglevel": "INFO",
      "logconfig" :
        { "appenders": [
            { "type": "console"
            }
          ]
        } // logconfig
    }
