apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etherpad-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem